### ISSUE TITLE
runrestic fails to parse valid `keep-within` values

### ISSUE THREAD

**Issue by saimonn** [sinnwerkstatt/runrestic#25]
```shell
runrestic -n
Problem parsing /etc/runrestic.toml: invalid literal for int() with base 0: '48h' (line 19 column 1 char 360)
```

restic assumes the parameter `keep-within` should be integer, which is not the case.

It's a duration, like `3w2d8h`

> --keep-within duration keep all snapshots which have been made within the duration of the latest snapshot. duration needs to be a number of years, months, days, and hours, e.g. 2y5m7d3h will keep all snapshots made in the two years, five months, seven days, and three hours before the latest snapshot.

**Comment by saimonn** [comment]
ok,. My bad, the value must be quoted, like `keep-within = "48h" `

Still, the code implicitly assume it's an integer, thus PR#26 should be merged .

**Comment by andreasnuesslein** [comment]
agreed - continue this in the #26
