### ISSUE TITLE
Use native bindings instead of string parsing

### ISSUE THREAD

**Issue by darkdragon-001** [sinnwerkstatt/runrestic#35]
Use [gopy](https://github.com/go-python/gopy) to create the bindings to [`restic/cmd/cmd_backup.go#runBackup(opts BackupOptions, gopts GlobalOptions, term *termstatus.Terminal, args []string)`](https://github.com/restic/restic/blob/master/cmd/restic/cmd_backup.go#L396). The same should be done for the other commands of course as well.

_[Structs](https://github.com/go-python/gopy/blob/master/_examples/structs)_ and _string [arrays](https://github.com/go-python/gopy/blob/master/_examples/arrays)_ should work out of the box, for [`termstatus.Terminal.New(wr io.Writer, errWriter io.Writer, disableStatus bool)`](https://github.com/restic/restic/blob/master/internal/ui/termstatus/status.go#L55) one needs to implement [`io.Writer`](https://golang.org/pkg/io/#Writer) interface which only needs a simple `Write(p []byte) (n int, err error)` which should call the python logger [callback](https://github.com/go-python/gopy/blob/master/_examples/funcs).

**Comment by darkdragon-001** [comment]
I wrote the go wrapper:

```go
package gopythonlogger

type PythonLogger struct {
    Fun func(str string)
}

func (logger *PythonLogger) Write(p []byte) (n int, err error) {
    logger.Fun(string(p))
    return len(p), nil
}

func New(fun func(str string)) *PythonLogger {
    return &PythonLogger { Fun: fun }
}
```

In Python, one can call it with
```python
import go, gopythonlogger

ioWriter = gopythonlogger.New(lambda s : logger.debug(s))
```

**Comment by andreasnuesslein** [comment]
:heart_eyes:  that looks awesome. I will look into that thanks

**Comment by andreasnuesslein** [comment]
Will use the API then, https://github.com/restic/restic/issues/2403 once that is implemented
