### ISSUE TITLE
Runrestic on Windows

### ISSUE THREAD

**Issue by yomono** [sinnwerkstatt/runrestic#42]
Hi!
After a few test I can conclude that runrestic is not runnable on Windows.

Is it possible to make it work on it?
It will be possible on the future? Is it planed?

Thank you in advance

**Comment by andreasnuesslein** [comment]
Hello @yomono ,

thanks for being interested in this. 

> Is it possible to make it work on it?

Quite possibly.

> It will be possible on the future? Is it planed?

I'm not planning on making anything Microsoft compatible, but if you can create a PR I could merge that.

**Comment by andreasnuesslein** [comment]
I'm closing this for now, but it does not mean I wouldn't accept such PRs.
