### ISSUE TITLE
Ansible role

### ISSUE THREAD

**Issue by tabic** [sinnwerkstatt/runrestic#45]
This is not an issue but might be relevant for anyone who is looking for a (run)restic ansible role. Thank you for this amazing restic wrapper!

I created an ansible role which install restic + runrestic and configures runrestic to create the backups, similar to what the [borgbase ansible role](https://github.com/borgbase/ansible-role-borgbackup) is for [borgmatic](https://github.com/witten/borgmatic).

GitHub: https://github.com/outwire/ansible-role-restic
Ansible Galaxy: https://galaxy.ansible.com/outwire/restic

**Comment by andreasnuesslein** [comment]
thank you, noted it in the README bf7fb6abce8ec6e96988c150a4cbe904ffe7abbf
