### ISSUE TITLE
Use return code from restic

### ISSUE THREAD

**Issue by Steffeng5** [sinnwerkstatt/runrestic#46]
When using runrestic within a cron job it would be helpful to look at the return code to notify the admin if the backup failed. But Runrestic always return zero. 

> [12:03:53 root@host] runrestic -l debug
Parsing configuration file: /etc/runrestic.toml
[Environment] RESTIC_PASSWORD=**********
Spawning "['restic', '-r', 'rest:xxx', 'backup', '/data', '/root']"
{'current_try': 1, 'tries_total': 1, 'output': [(1, 'Fatal: wrong password or no key found\n')], 'time': 0.5132162570953369}
Spawning "['restic', '-r', 'rest:xxx', 'forget', '--keep-last', '3', '--keep-hourly', '5', '--keep-daily', '7', '--keep-weekly', '8', '--keep-monthly', '6', '--keep-yearly', '11']"
[(1, 'Fatal: wrong password or no key found\n')]
Spawning "['restic', '-r', 'rest:xxx', 'prune']"
[(1, 'Fatal: wrong password or no key found\n')]
Spawning "['restic', '-r', 'rest:xxx', 'check']"
[(1, 'using temporary cache in /tmp/restic-check-cache-545556970\nFatal: wrong password or no key found\n')]
{
  "errors": 4,
  "backup": {
    "rest:xxx": {
      "rc": 1
    }
  },
  "forget": {
    "rest:xxx": {
      "rc": 1
    }
  },
  "prune": {
    "rest:xxx": {
      "rc": 1
    }
  },
  "check": {
    "rest:xxx": {
      "errors": 0,
      "errors_data": 0,
      "errors_snapshots": 0,
      "read_data": 0,
      "check_unused": 0,
      "duration_seconds": 0.5457494258880615,
      "rc": 1
    }
  },
  "last_run": 1628157841.395445,
  "total_duration_seconds": 2.183987855911255
}
[12:04:01 root@host] echo $?
0

**Comment by FlxPeters** [comment]
Same issue here. Any idea how to solve this? 
I think a new config flag would be required to have a non breaking change.

**Comment by FlxPeters** [comment]
@andreasnuesslein What do you think about this issue? I have an idea how to implement this, but this would introduce an breaking change. Any failed job would exit the whole process with exit code 1.

Another approach would be some kind of soft fail where runrestic tries to finish all jobs and returns a non zero exit code depending on the result of all jobs.

**Comment by bjo81** [comment]
I wrapped runrestic with runitor to minitor the process with healthchecks.io and was wondering why returns "ok" even with restic exiting with 1.

**Comment by palto42** [comment]
This issue has been address in #52.
