### ISSUE TITLE
Support of S3 backend

### ISSUE THREAD

**Issue by vin-6** [sinnwerkstatt/runrestic#48]
Hi 👋,

I'm trying to setup runrestic to push my backup in S3.
By reading the [sample config file](https://github.com/sinnwerkstatt/runrestic/blob/41715c78dd82e26d62a6e917ce73079bae05dd69/sample/example.toml#L17-L20), it's not clear to me in you support all environments variables or only `RESTIC_PASSWORD` and RESTIC_PASSWORD_FILE` ?

[The schema.json](https://github.com/sinnwerkstatt/runrestic/blob/41715c78dd82e26d62a6e917ce73079bae05dd69/runrestic/runrestic/schema.json#L39) file into your code let me think it's not supported by I prefer to ask.
If it's not supported, do you plan to do so ?

**Comment by andreasnuesslein** [comment]
also hi :)

any key that you set in `[environment]` will be added to the environment 

https://github.com/sinnwerkstatt/runrestic/blob/master/runrestic/restic/tools.py#L84

hth

**Comment by vin-6** [comment]
Thank you for your answer.
It's probably a miss configuration from my side. I'll check
