### ISSUE TITLE
Support Python 3.10 - EOL of Python 3.6

### ISSUE THREAD

**Issue by palto42** [sinnwerkstatt/runrestic#56]
Hi @andreasnuesslein,
What do you think of a general version update for this module since [Python 3.6 is end of life](https://devguide.python.org/devcycle/#end-of-life-branches) already and latest Python is meanwhile 3.10?

The main changes in my view would be:

* Change min supported version to 3.8 (or 3.7?)
* Update the dependencies (poetry.lock)
* Change versions tested in Travis to 3.8, 3.9 and 3.10

I'm not expecting any direct impact on the code, it would be mainly to catch-up with Python release cycle.
Since my main laptop uses Python 3.10 I've already using an update version of runrestic, including updated dependencies via Poetry.

**Comment by andreasnuesslein** [comment]
Sounds super. Let's support 3.7 too, because that one is not "end of life" yet

**Comment by palto42** [comment]
Will update to support py3.7 - py3.10 , currently testing the updated version on my branch [palto42/runrestic : upgrade_py3.7-3.10](https://github.com/palto42/runrestic/tree/upgrade_py3.7-3.10).

**Comment by palto42** [comment]
delivered with #57
