### ISSUE TITLE
Can we allow jsonschema >= 4?

### ISSUE THREAD

**Issue by darix** [sinnwerkstatt/runrestic#67]
or is there anything that blocks the upgrade?

**Comment by palto42** [comment]
@darix Any specific reason for upgrading jsonschema?

I tried an upgrade on my branch https://github.com/palto42/runrestic/tree/poetry_update and all tests passed, so seems to work in principle.

**Comment by darix** [comment]
so distributions can move forward and dont need to be stuck on older versions?

**Comment by palto42** [comment]
@andreasnuesslein Any reason why in `setup.py` specified  `install_requires=["jsonschema>=3.0,<4.0",]` ?
Was the reason maybe that [`jsonschema` 4.0 dropped support for Python 3.6](https://github.com/python-jsonschema/jsonschema/blob/main/CHANGELOG.rst#v400) which was still desired at that time? Meanwhile `runrestic` also dropped 3.6, so there would be no blocker for `jsonschema `>=4

**Comment by andreasnuesslein** [comment]
no, i don't remember any other reason. thanks so much for investigating @palto42

**Comment by andreasnuesslein** [comment]
tadaa https://github.com/sinnwerkstatt/runrestic/releases/tag/0.5.28
